"""source_sytem

Revision ID: 2d2c8a43d72b
Revises: a6a47362bf14
Create Date: 2019-01-29 22:05:35.356224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2c8a43d72b'
down_revision = 'a6a47362bf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_system_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('source_system_id', 'source_system', ['source_system_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_system_id')

    op.drop_table('source_system')
    # ### end Alembic commands ###
