"""init

Revision ID: 728123777393
Revises: 
Create Date: 2019-01-29 21:00:19.660619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728123777393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_en',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_ru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_to_level',
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('name_en_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language_level.id'], ),
    sa.ForeignKeyConstraint(['name_en_id'], ['name_en.id'], )
    )
    op.create_table('ru_to_en',
    sa.Column('name_ru_id', sa.Integer(), nullable=True),
    sa.Column('name_en_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name_en_id'], ['name_en.id'], ),
    sa.ForeignKeyConstraint(['name_ru_id'], ['name_ru.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['language_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_to_user',
    sa.Column('name_en_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name_en_id'], ['name_en.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_to_user')
    op.drop_table('users')
    op.drop_table('ru_to_en')
    op.drop_table('language_to_level')
    op.drop_table('name_ru')
    op.drop_table('name_en')
    op.drop_table('language_level')
    # ### end Alembic commands ###
