"""timestamp

Revision ID: a6a47362bf14
Revises: 728123777393
Create Date: 2019-01-29 21:30:12.734944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a47362bf14'
down_revision = '728123777393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_to_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_create', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_to_user', schema=None) as batch_op:
        batch_op.drop_column('time_update')
        batch_op.drop_column('time_create')

    # ### end Alembic commands ###
